/**
 * Emitter golden / substring assertions for representative IR (ADR-0019 slice 3).
 * Node-level Persisted* walkers are package-internal — assert via emitContentConfig.
 */

import { describe, expect, test } from "bun:test";
import { compileSemanticIr, s } from "@cms/core/semantic";
import { emitContentConfig } from "../src/generate/emit-content-config.ts";
import { HASH_MARKER } from "../src/generate/hash.ts";

describe("emitContentConfig", () => {
	test("emits native Astro source for representative IR (image, reference, optional, nested, glob)", () => {
		const ir = compileSemanticIr({
			collections: {
				posts: s.collection({
					loader: s.glob({
						base: "./src/content/posts",
						pattern: "**/*.json",
					}),
					schema: s.stack([
						s.field({ id: "title", schema: s.string().min(1) }),
						s.field({ id: "body", schema: s.string() }),
						s.field({ id: "cover", schema: s.image().optional() }),
						s.field({ id: "author", schema: s.reference("authors") }),
						s.object({
							id: "seo",
							content: [
								s.field({
									id: "title",
									schema: s.string().max(70),
								}),
								s.field({
									id: "description",
									schema: s.string().max(160),
								}),
							],
						}),
						s.discriminatedUnion({
							id: "block",
							discriminant: "type",
							variants: [
								s.object({
									id: "text",
									content: [s.field({ id: "body", schema: s.string() })],
								}),
								s.object({
									id: "quote",
									content: [s.field({ id: "cite", schema: s.string() })],
								}),
							],
						}),
					]),
				}),
				authors: s.collection({
					loader: s.glob({
						base: "./src/content/authors",
						pattern: "**/*.json",
					}),
					schema: s.field({ id: "name", schema: s.string().min(1) }),
				}),
			},
		});

		const source = emitContentConfig(ir, {
			sourceHash: "a".repeat(64),
		});

		expect(
			source.startsWith("// Generated by Astro Dev CMS. Do not edit."),
		).toBe(true);
		expect(source).toContain(`// ${HASH_MARKER} ${"a".repeat(64)}`);
		expect(source).toContain('from "astro:content"');
		expect(source).toContain('from "astro/loaders"');
		expect(source).toContain('from "astro/zod"');
		expect(source).toContain("defineCollection");
		expect(source).toContain("reference");
		expect(source).toContain("type SchemaContext");
		expect(source).toContain(
			"export const postsSchema = ({ image }: SchemaContext) =>",
		);
		expect(source).toContain("title: z.string().min(1)");
		expect(source).toContain("cover: image().optional()");
		expect(source).toContain('author: reference("authors")');
		expect(source).toContain("seo: z.object({");
		expect(source).toContain('z.discriminatedUnion("type"');
		expect(source).toContain('type: z.literal("text")');
		expect(source).toContain('type: z.literal("quote")');
		expect(source).toContain(
			`loader: glob({\n\t\tbase: "./src/content/posts",\n\t\tpattern: "**/*.json",\n\t})`,
		);
		expect(source).toContain("export const authorsSchema = z.object({");
		expect(source).toContain("name: z.string().min(1)");
		expect(source).toContain("export const collections = { authors, posts };");
		expect(source).not.toContain("ZodTypeAny");
		expect(source).not.toMatch(/\bas\s+/);
	});

	test("strips presentation — header/separator/tabs do not appear as fields", () => {
		const ir = compileSemanticIr({
			collections: {
				posts: s.collection({
					loader: s.glob({ base: "./c", pattern: "**/*.json" }),
					schema: s.tabs([
						s.tab({
							id: "main",
							label: "Main",
							content: [
								s.header({ label: "Ignore" }),
								s.separator(),
								s.field({ id: "title", schema: s.string() }),
							],
						}),
					]),
				}),
			},
		});

		const source = emitContentConfig(ir);
		expect(source).toContain("title: z.string()");
		expect(source).not.toContain("Ignore");
		expect(source).not.toContain("header");
		expect(source).not.toContain("separator");
	});

	test("emits scalar wrappers and constraints via collection plan", () => {
		const ir = compileSemanticIr({
			collections: {
				posts: s.collection({
					loader: s.glob({ base: "./c", pattern: "**/*.json" }),
					schema: s.stack([
						s.field({
							id: "title",
							schema: s.string().min(1).max(70),
						}),
						s.field({
							id: "score",
							schema: s.number().int().min(0).max(10),
						}),
						s.field({ id: "draft", schema: s.boolean().default(false) }),
						s.field({ id: "kind", schema: s.enum(["a", "b"]) }),
						s.field({ id: "cover", schema: s.image().optional() }),
						s.field({ id: "note", schema: s.string().nullable() }),
					]),
				}),
			},
		});
		const source = emitContentConfig(ir);
		expect(source).toContain("title: z.string().min(1).max(70)");
		expect(source).toContain("score: z.number().int().min(0).max(10)");
		expect(source).toContain("draft: z.boolean().default(false)");
		expect(source).toContain('kind: z.enum(["a", "b"])');
		expect(source).toContain("cover: image().optional()");
		expect(source).toContain("note: z.string().nullable()");
	});
});
