/**
 * Emit native Astro `content.config.ts` source from compiled semantic IR.
 *
 * Walks the presentation-stripped persisted shape (ADR-0019). No ZodTypeAny,
 * broad casts, or type assertions in the generated source.
 */

import type {
	CompiledSemanticIr,
	PersistedField,
	PersistedSchema,
} from "@cms/core/semantic";
import { HASH_MARKER } from "./hash";

export type EmitContentConfigOptions = {
	/** SHA-256 hex embedded after the header (optional — generate supplies it). */
	sourceHash?: string;
	/** Override the "Generated by …" header line. */
	generatedBy?: string;
};

const DEFAULT_GENERATED_BY = "Astro Dev CMS. Do not edit.";

/** Valid JS identifier — used bare as object keys / const names. */
const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propKey(id: string): string {
	return IDENT_RE.test(id) ? id : JSON.stringify(id);
}

function schemaConstName(collectionId: string): string {
	if (!IDENT_RE.test(collectionId)) {
		throw new Error(
			`Collection id ${JSON.stringify(collectionId)} is not a valid JS identifier; cannot emit schema const`,
		);
	}
	return `${collectionId}Schema`;
}

function emitJsLiteral(value: unknown): string {
	if (value === null) return "null";
	switch (typeof value) {
		case "string":
		case "number":
		case "boolean":
			return JSON.stringify(value);
		case "undefined":
			return "undefined";
		default:
			throw new Error(
				`Cannot emit default value of type ${typeof value} (v1 allows string | number | boolean | null)`,
			);
	}
}

function schemaNeedsImage(schema: PersistedSchema): boolean {
	switch (schema.kind) {
		case "image":
			return true;
		case "optional":
		case "nullable":
		case "default":
			return schemaNeedsImage(schema.of);
		case "array":
			return schemaNeedsImage(schema.of);
		case "object":
			return schema.fields.some((f) => schemaNeedsImage(f.schema));
		case "discriminatedUnion":
			return schema.variants.some((v) =>
				v.fields.some((f) => schemaNeedsImage(f.schema)),
			);
		case "string":
		case "number":
		case "boolean":
		case "literal":
		case "enum":
		case "reference":
			return false;
		default: {
			const _exhaustive: never = schema;
			return _exhaustive;
		}
	}
}

function schemaNeedsReference(schema: PersistedSchema): boolean {
	switch (schema.kind) {
		case "reference":
			return true;
		case "optional":
		case "nullable":
		case "default":
			return schemaNeedsReference(schema.of);
		case "array":
			return schemaNeedsReference(schema.of);
		case "object":
			return schema.fields.some((f) => schemaNeedsReference(f.schema));
		case "discriminatedUnion":
			return schema.variants.some((v) =>
				v.fields.some((f) => schemaNeedsReference(f.schema)),
			);
		case "string":
		case "number":
		case "boolean":
		case "literal":
		case "enum":
		case "image":
			return false;
		default: {
			const _exhaustive: never = schema;
			return _exhaustive;
		}
	}
}

function collectionNeedsImage(fields: readonly PersistedField[]): boolean {
	return fields.some((f) => schemaNeedsImage(f.schema));
}

function fieldsNeedReference(fields: readonly PersistedField[]): boolean {
	return fields.some((f) => schemaNeedsReference(f.schema));
}

function emitConstraints(
	base: string,
	schema: Extract<PersistedSchema, { kind: "string" | "number" }>,
): string {
	let out = base;
	for (const c of schema.constraints) {
		switch (c.method) {
			case "min":
				out += `.min(${c.value})`;
				break;
			case "max":
				out += `.max(${c.value})`;
				break;
			case "int":
				out += `.int()`;
				break;
			case "regex":
				out += `.regex(new RegExp(${JSON.stringify(c.source)}, ${JSON.stringify(c.flags)}))`;
				break;
			default: {
				const _exhaustive: never = c;
				throw new Error(
					`Unexpected constraint: ${JSON.stringify(_exhaustive)}`,
				);
			}
		}
	}
	return out;
}

/**
 * Emit a Zod expression for one persisted schema node.
 * Fail-closed on unexpected IR.
 */
export function emitPersistedSchema(schema: PersistedSchema): string {
	switch (schema.kind) {
		case "string":
			return emitConstraints("z.string()", schema);
		case "number":
			return emitConstraints("z.number()", schema);
		case "boolean":
			return "z.boolean()";
		case "literal":
			return `z.literal(${emitJsLiteral(schema.value)})`;
		case "enum":
			return `z.enum([${schema.values.map((v) => JSON.stringify(v)).join(", ")}])`;
		case "image":
			return "image()";
		case "reference":
			return `reference(${JSON.stringify(schema.collection)})`;
		case "optional":
			return `${emitPersistedSchema(schema.of)}.optional()`;
		case "nullable":
			return `${emitPersistedSchema(schema.of)}.nullable()`;
		case "default":
			return `${emitPersistedSchema(schema.of)}.default(${emitJsLiteral(schema.value)})`;
		case "object":
			return emitObjectFields(schema.fields);
		case "array":
			return `z.array(${emitPersistedSchema(schema.of)})`;
		case "discriminatedUnion": {
			if (schema.variants.length === 0) {
				throw new Error(
					`discriminatedUnion "${schema.discriminant}" has no variants`,
				);
			}
			const variants = schema.variants
				.map((v) => `\t${emitObjectFields(v.fields)},`)
				.join("\n");
			return `z.discriminatedUnion(${JSON.stringify(schema.discriminant)}, [\n${variants}\n])`;
		}
		default: {
			const _exhaustive: never = schema;
			throw new Error(
				`Unexpected persisted IR node: ${JSON.stringify(_exhaustive)}`,
			);
		}
	}
}

function emitObjectFields(fields: readonly PersistedField[]): string {
	if (fields.length === 0) {
		return "z.object({})";
	}
	const lines = fields.map(
		(f) => `\t${propKey(f.id)}: ${emitPersistedSchema(f.schema)},`,
	);
	return `z.object({\n${lines.join("\n")}\n})`;
}

function emitCollectionSchemaExpr(
	fields: readonly PersistedField[],
	needsImage: boolean,
): string {
	const body = emitObjectFields(fields);
	if (!needsImage) {
		return body;
	}
	// Indent body one tab under the SchemaContext arrow.
	const indented = body
		.split("\n")
		.map((line, i) => (i === 0 ? line : `\t${line}`))
		.join("\n");
	return `({ image }: SchemaContext) =>\n\t${indented}`;
}

/**
 * Render full `content.config.ts` TypeScript source from compiled IR.
 */
export function emitContentConfig(
	ir: CompiledSemanticIr,
	options: EmitContentConfigOptions = {},
): string {
	const generatedBy = options.generatedBy ?? DEFAULT_GENERATED_BY;
	const collectionIds = Object.keys(ir.persisted).sort();

	const anyImage = collectionIds.some((id) => {
		const shape = ir.persisted[id];
		return shape !== undefined && collectionNeedsImage(shape.fields);
	});
	const anyReference = collectionIds.some((id) =>
		fieldsNeedReference(ir.persisted[id]?.fields ?? []),
	);

	const contentImports = ["defineCollection"];
	if (anyReference) {
		contentImports.push("reference");
	}
	if (anyImage) {
		contentImports.push("type SchemaContext");
	}

	const imports = [
		`import {\n\t${contentImports.join(",\n\t")},\n} from "astro:content";`,
		`import { glob } from "astro/loaders";`,
		`import { z } from "astro/zod";`,
	];

	const schemaDecls: string[] = [];
	const collectionDecls: string[] = [];

	for (const id of collectionIds) {
		const persisted = ir.persisted[id];
		const collection = ir.collections[id];
		if (persisted === undefined) {
			throw new Error(`Missing persisted shape for collection "${id}"`);
		}
		const loader = collection?.loader ?? persisted.loader;
		if (loader.kind !== "glob") {
			throw new Error(
				`Loader "${(loader as { kind: string }).kind}" is not supported (v1 allows glob only)`,
			);
		}

		const needsImage = collectionNeedsImage(persisted.fields);
		const constName = schemaConstName(id);
		const schemaExpr = emitCollectionSchemaExpr(persisted.fields, needsImage);

		schemaDecls.push(`export const ${constName} = ${schemaExpr};\n`);

		collectionDecls.push(
			[
				`const ${id} = defineCollection({`,
				`\tloader: glob({`,
				`\t\tbase: ${JSON.stringify(loader.base)},`,
				`\t\tpattern: ${JSON.stringify(loader.pattern)},`,
				`\t}),`,
				`\tschema: ${constName},`,
				`});`,
			].join("\n"),
		);
	}

	const collectionsExport =
		collectionIds.length === 0
			? "export const collections = {};"
			: `export const collections = { ${collectionIds.join(", ")} };`;

	const header = [`// Generated by ${generatedBy}`];
	if (options.sourceHash !== undefined) {
		header.push(`// ${HASH_MARKER} ${options.sourceHash}`);
	}

	return [
		...header,
		"",
		...imports,
		"",
		...schemaDecls,
		...collectionDecls,
		"",
		collectionsExport,
		"",
	].join("\n");
}
