/**
 * Emit native Astro `content.config.ts` source from compiled semantic IR.
 *
 * Schema expressions come from `persistedProjections(ir).astroSchemaPlan()`
 * (ADR-0010 / 0019). This module only renders the plan + file shell.
 */

import {
	type AstroSchemaExpr,
	type AstroSchemaPlan,
	type CompiledSemanticIr,
	type PersistedSchema,
	persistedProjections,
	projectAstroSchemaExpr,
} from "@cms/core/semantic";
import { HASH_MARKER } from "./hash";

export type EmitContentConfigOptions = {
	/** SHA-256 hex embedded after the header (optional — generate supplies it). */
	sourceHash?: string;
	/** Override the "Generated by …" header line. */
	generatedBy?: string;
};

const DEFAULT_GENERATED_BY = "Astro Dev CMS. Do not edit.";

/** Valid JS identifier — used bare as object keys / const names. */
const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propKey(id: string): string {
	return IDENT_RE.test(id) ? id : JSON.stringify(id);
}

function schemaConstName(collectionId: string): string {
	if (!IDENT_RE.test(collectionId)) {
		throw new Error(
			`Collection id ${JSON.stringify(collectionId)} is not a valid JS identifier; cannot emit schema const`,
		);
	}
	return `${collectionId}Schema`;
}

function emitJsLiteral(value: unknown): string {
	if (value === null) return "null";
	switch (typeof value) {
		case "string":
		case "number":
		case "boolean":
			return JSON.stringify(value);
		case "undefined":
			return "undefined";
		default:
			throw new Error(
				`Cannot emit default value of type ${typeof value} (v1 allows string | number | boolean | null)`,
			);
	}
}

function emitConstraints(
	base: string,
	constraints: readonly {
		readonly method: string;
		readonly value?: number;
		readonly source?: string;
		readonly flags?: string;
	}[],
): string {
	let out = base;
	for (const c of constraints) {
		switch (c.method) {
			case "min":
				out += `.min(${c.value})`;
				break;
			case "max":
				out += `.max(${c.value})`;
				break;
			case "int":
				out += `.int()`;
				break;
			case "regex":
				out += `.regex(new RegExp(${JSON.stringify(c.source)}, ${JSON.stringify(c.flags)}))`;
				break;
			default:
				throw new Error(`Unexpected constraint: ${JSON.stringify(c)}`);
		}
	}
	return out;
}

/**
 * Render one Astro schema expression to a Zod/Astro source fragment.
 */
export function renderAstroSchemaExpr(expr: AstroSchemaExpr): string {
	switch (expr.tag) {
		case "string":
			return emitConstraints("z.string()", expr.constraints);
		case "number":
			return emitConstraints("z.number()", expr.constraints);
		case "boolean":
			return "z.boolean()";
		case "literal":
			return `z.literal(${emitJsLiteral(expr.value)})`;
		case "enum":
			return `z.enum([${expr.values.map((v) => JSON.stringify(v)).join(", ")}])`;
		case "image":
			return "image()";
		case "reference":
			return `reference(${JSON.stringify(expr.collection)})`;
		case "optional":
			return `${renderAstroSchemaExpr(expr.of)}.optional()`;
		case "nullable":
			return `${renderAstroSchemaExpr(expr.of)}.nullable()`;
		case "default":
			return `${renderAstroSchemaExpr(expr.of)}.default(${emitJsLiteral(expr.value)})`;
		case "array":
			return `z.array(${renderAstroSchemaExpr(expr.of)})`;
		case "object":
			return emitObjectFields(expr.fields);
		case "discriminatedUnion": {
			if (expr.variants.length === 0) {
				throw new Error(
					`discriminatedUnion "${expr.discriminant}" has no variants`,
				);
			}
			const variants = expr.variants
				.map((v) => `\t${emitObjectFields(v.fields)},`)
				.join("\n");
			return `z.discriminatedUnion(${JSON.stringify(expr.discriminant)}, [\n${variants}\n])`;
		}
		default: {
			const _exhaustive: never = expr;
			throw new Error(
				`Unexpected Astro schema expr: ${JSON.stringify(_exhaustive)}`,
			);
		}
	}
}

function emitObjectFields(
	fields: readonly { readonly id: string; readonly schema: AstroSchemaExpr }[],
): string {
	if (fields.length === 0) {
		return "z.object({})";
	}
	const lines = fields.map(
		(f) => `\t${propKey(f.id)}: ${renderAstroSchemaExpr(f.schema)},`,
	);
	return `z.object({\n${lines.join("\n")}\n})`;
}

/**
 * Emit a Zod expression for one persisted schema node.
 * Projects through the shared IR walker, then renders.
 */
export function emitPersistedSchema(schema: PersistedSchema): string {
	try {
		return renderAstroSchemaExpr(projectAstroSchemaExpr(schema));
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		if (message.includes("Unexpected persisted IR node")) {
			throw new Error(`Unexpected persisted IR node: ${message}`);
		}
		throw err;
	}
}

function emitCollectionSchemaExpr(
	root: AstroSchemaExpr,
	needsImage: boolean,
): string {
	const body = renderAstroSchemaExpr(root);
	if (!needsImage) {
		return body;
	}
	const indented = body
		.split("\n")
		.map((line, i) => (i === 0 ? line : `\t${line}`))
		.join("\n");
	return `({ image }: SchemaContext) =>\n\t${indented}`;
}

function renderContentConfigFile(
	plan: AstroSchemaPlan,
	ir: CompiledSemanticIr,
	options: EmitContentConfigOptions,
): string {
	const generatedBy = options.generatedBy ?? DEFAULT_GENERATED_BY;
	const { collectionIds, needsImage, needsReference } = plan;

	const contentImports = ["defineCollection"];
	if (needsReference) {
		contentImports.push("reference");
	}
	if (needsImage) {
		contentImports.push("type SchemaContext");
	}

	const imports = [
		`import {\n\t${contentImports.join(",\n\t")},\n} from "astro:content";`,
		`import { glob } from "astro/loaders";`,
		`import { z } from "astro/zod";`,
	];

	const schemaDecls: string[] = [];
	const collectionDecls: string[] = [];

	for (const id of collectionIds) {
		const collectionPlan = plan.byCollection[id];
		const collection = ir.collections[id];
		const persisted = ir.persisted[id];
		if (collectionPlan === undefined || persisted === undefined) {
			throw new Error(`Missing persisted shape for collection "${id}"`);
		}
		const loader = collection?.loader ?? persisted.loader;
		if (loader.kind !== "glob") {
			throw new Error(
				`Loader "${(loader as { kind: string }).kind}" is not supported (v1 allows glob only)`,
			);
		}

		const constName = schemaConstName(id);
		const schemaExpr = emitCollectionSchemaExpr(
			collectionPlan.root,
			collectionPlan.needsImage,
		);

		schemaDecls.push(`export const ${constName} = ${schemaExpr};\n`);

		collectionDecls.push(
			[
				`const ${id} = defineCollection({`,
				`\tloader: glob({`,
				`\t\tbase: ${JSON.stringify(loader.base)},`,
				`\t\tpattern: ${JSON.stringify(loader.pattern)},`,
				`\t}),`,
				`\tschema: ${constName},`,
				`});`,
			].join("\n"),
		);
	}

	const collectionsExport =
		collectionIds.length === 0
			? "export const collections = {};"
			: `export const collections = { ${collectionIds.join(", ")} };`;

	const header = [`// Generated by ${generatedBy}`];
	if (options.sourceHash !== undefined) {
		header.push(`// ${HASH_MARKER} ${options.sourceHash}`);
	}

	return [
		...header,
		"",
		...imports,
		"",
		...schemaDecls,
		...collectionDecls,
		"",
		collectionsExport,
		"",
	].join("\n");
}

/**
 * Render full `content.config.ts` TypeScript source from compiled IR.
 */
export function emitContentConfig(
	ir: CompiledSemanticIr,
	options: EmitContentConfigOptions = {},
): string {
	return renderContentConfigFile(
		persistedProjections(ir).astroSchemaPlan(),
		ir,
		options,
	);
}
