/**
 * Closed semantic IR for CMS-first schemas (ADR-0019).
 *
 * Primary seam: `compileSemanticIr` (+ `s` builders, `persistedShape`).
 * No Svelte; no Astro emission.
 */

export {
	type ArrayNode,
	type BooleanNode,
	type CollectionNode,
	type ColumnNode,
	type ColumnsNode,
	type DefaultNode,
	type DiscriminatedUnionNode,
	type EnumNode,
	type FieldNode,
	type GlobLoaderNode,
	type GroupNode,
	type HeaderNode,
	type ImageNode,
	isSemanticNode,
	type LiteralNode,
	type NullableNode,
	type NumberNode,
	type ObjectNode,
	type OptionalNode,
	type ReferenceNode,
	type SchemaNode,
	SEMANTIC_NODE,
	type SemanticConfigInput,
	type SeparatorNode,
	type StackNode,
	type StringNode,
	s,
	type TabNode,
	type TabsNode,
	type TreeNode,
} from "./builders";
export { compileSemanticIr, persistedShape } from "./compile";
export { SemanticIrError, type SemanticIrIssue } from "./errors";
export type {
	CompiledSemanticIr,
	IrArray,
	IrBoolean,
	IrCollection,
	IrColumn,
	IrColumns,
	IrDefault,
	IrDiscriminatedUnion,
	IrEnum,
	IrField,
	IrGlobLoader,
	IrGroup,
	IrHeader,
	IrImage,
	IrLiteral,
	IrNullable,
	IrNumber,
	IrObject,
	IrOptional,
	IrReference,
	IrSchema,
	IrSeparator,
	IrStack,
	IrString,
	IrTab,
	IrTabs,
	IrTreeNode,
	NumberConstraint,
	OpaqueBinding,
	OpaqueProps,
	PersistedArray,
	PersistedCollectionShape,
	PersistedConfigShape,
	PersistedDefault,
	PersistedDiscriminatedUnion,
	PersistedField,
	PersistedNullable,
	PersistedObject,
	PersistedOptional,
	PersistedSchema,
	ScalarConstraint,
	SemanticKind,
	StringConstraint,
} from "./types";
