/**
 * Closed semantic IR for CMS-first schemas (ADR-0019).
 *
 * Primary seam: `compileSemanticIr` (+ `s` builders).
 * Projections: `persistedProjections`, `projectFormModels`, `createAuthoritativeValidator`.
 * No Svelte; no Astro emission. Persisted* format and node walkers are package-internal.
 */

export {
	type ArrayNode,
	type BindableArrayNode,
	type BindableFieldNode,
	type BindableObjectNode,
	type BooleanNode,
	type CollectionNode,
	type ColumnNode,
	type ColumnsNode,
	type DefaultNode,
	type DiscriminatedUnionNode,
	type EnumNode,
	type FieldNode,
	type GlobLoaderNode,
	type GroupNode,
	type HeaderNode,
	type ImageNode,
	isSemanticNode,
	type LiteralNode,
	type NullableNode,
	type NumberNode,
	type ObjectNode,
	type OptionalNode,
	type ReferenceNode,
	type SchemaNode,
	SEMANTIC_NODE,
	type SemanticConfigInput,
	type SeparatorNode,
	type StackNode,
	type StringNode,
	s,
	type TabNode,
	type TabsNode,
	type TreeNode,
} from "./builders";
export { compileSemanticIr } from "./compile";
export { SemanticIrError, type SemanticIrIssue } from "./errors";
export {
	type CollectionFormModel,
	type FormConstraintSummary,
	type FormFieldDescriptor,
	type FormLayoutArray,
	type FormLayoutColumn,
	type FormLayoutColumns,
	type FormLayoutFieldRef,
	type FormLayoutGroup,
	type FormLayoutHeader,
	type FormLayoutNode,
	type FormLayoutObject,
	type FormLayoutSeparator,
	type FormLayoutStack,
	type FormLayoutTab,
	type FormLayoutTabs,
	type FormLayoutUnion,
	type FormLayoutUnionVariant,
	type FormModelsByCollection,
	projectCollectionFormModel,
	projectFormModels,
} from "./form-model";
export {
	type AstroCollectionSchemaPlan,
	type AstroSchemaConstraint,
	type AstroSchemaExpr,
	type AstroSchemaPlan,
	type AuthoritativeValidatorDeps,
	type JsonSchema,
	type PersistedProjections,
	persistedProjections,
} from "./persisted-projections";
export type {
	CompiledSemanticIr,
	IrArray,
	IrBoolean,
	IrCollection,
	IrColumn,
	IrColumns,
	IrDefault,
	IrDiscriminatedUnion,
	IrEnum,
	IrField,
	IrGlobLoader,
	IrGroup,
	IrHeader,
	IrImage,
	IrLiteral,
	IrNullable,
	IrNumber,
	IrObject,
	IrOptional,
	IrReference,
	IrSchema,
	IrSeparator,
	IrStack,
	IrString,
	IrTab,
	IrTabs,
	IrTreeNode,
	NumberConstraint,
	OpaqueBinding,
	OpaqueProps,
	ScalarConstraint,
	SemanticKind,
	StringConstraint,
} from "./types";
export {
	type AuthoritativeParseIssue,
	type AuthoritativeParseResult,
	type AuthoritativeValidator,
	createAuthoritativeValidator,
} from "./validator";
export {
	CONTENT_FIELD_STAMP,
	type ContentFieldStampMeta,
	type ProjectSchemaFormModelsOptions,
	type ProjectSchemaFormOptions,
	type SchemaFormFieldChrome,
	type SchemaFormOverlay,
	applySchemaFormOverlay,
	projectSchemaFormModel,
	projectSchemaFormModels,
} from "./schema-form-projection";
