/**
 * Closed semantic IR for CMS-first schemas (ADR-0019).
 *
 * Primary seam: `compileSemanticIr` (+ `s` builders, `persistedShape`).
 * Projections: `persistedProjections`, `projectFormModels`, `createAuthoritativeValidator`.
 * No Svelte; no Astro emission.
 */

export {
	type ArrayNode,
	type BooleanNode,
	type CollectionNode,
	type ColumnNode,
	type ColumnsNode,
	type DefaultNode,
	type DiscriminatedUnionNode,
	type EnumNode,
	type FieldNode,
	type GlobLoaderNode,
	type GroupNode,
	type HeaderNode,
	type ImageNode,
	isSemanticNode,
	type LiteralNode,
	type NullableNode,
	type NumberNode,
	type ObjectNode,
	type OptionalNode,
	type ReferenceNode,
	type SchemaNode,
	SEMANTIC_NODE,
	type SemanticConfigInput,
	type SeparatorNode,
	type StackNode,
	type StringNode,
	s,
	type TabNode,
	type TabsNode,
	type TreeNode,
} from "./builders";
export { compileSemanticIr, persistedShape } from "./compile";
export { SemanticIrError, type SemanticIrIssue } from "./errors";
export {
	type CollectionFormModel,
	type FormConstraintSummary,
	type FormFieldDescriptor,
	type FormLayoutArray,
	type FormLayoutColumn,
	type FormLayoutColumns,
	type FormLayoutFieldRef,
	type FormLayoutGroup,
	type FormLayoutHeader,
	type FormLayoutNode,
	type FormLayoutObject,
	type FormLayoutSeparator,
	type FormLayoutStack,
	type FormLayoutTab,
	type FormLayoutTabs,
	type FormLayoutUnion,
	type FormLayoutUnionVariant,
	type FormModelsByCollection,
	projectCollectionFormModel,
	projectFormModels,
} from "./form-model";
export {
	type AstroCollectionSchemaPlan,
	type AstroSchemaConstraint,
	type AstroSchemaExpr,
	type AstroSchemaPlan,
	type AuthoritativeValidatorDeps,
	type JsonSchema,
	type PersistedProjections,
	persistedProjections,
	projectAstroSchemaExpr,
} from "./persisted-projections";
export type {
	CompiledSemanticIr,
	IrArray,
	IrBoolean,
	IrCollection,
	IrColumn,
	IrColumns,
	IrDefault,
	IrDiscriminatedUnion,
	IrEnum,
	IrField,
	IrGlobLoader,
	IrGroup,
	IrHeader,
	IrImage,
	IrLiteral,
	IrNullable,
	IrNumber,
	IrObject,
	IrOptional,
	IrReference,
	IrSchema,
	IrSeparator,
	IrStack,
	IrString,
	IrTab,
	IrTabs,
	IrTreeNode,
	NumberConstraint,
	OpaqueBinding,
	OpaqueProps,
	PersistedArray,
	PersistedCollectionShape,
	PersistedConfigShape,
	PersistedDefault,
	PersistedDiscriminatedUnion,
	PersistedField,
	PersistedNullable,
	PersistedObject,
	PersistedOptional,
	PersistedSchema,
	ScalarConstraint,
	SemanticKind,
	StringConstraint,
} from "./types";
export { stripUiFromJsonSchema, type UiSchemaNode } from "./ui-schema";
export {
	type AuthoritativeParseIssue,
	type AuthoritativeParseResult,
	type AuthoritativeValidator,
	createAuthoritativeValidator,
} from "./validator";
