/**
 * Emit `src/cms.types.d.ts` augmenting `@cms/astro/collection-types`.
 */

import type { z } from "zod";
import {
	type CollectionTypePrint,
	printFieldKindsObject,
	printZodInputType,
} from "./zod-input-type";

export const CMS_COLLECTION_TYPES_FILENAME = "cms.types.d.ts";

export function printCollectionTypesFile(
	collections: Readonly<Record<string, z.ZodType>>,
): string {
	const printed: CollectionTypePrint[] = [];
	for (const [name, schema] of Object.entries(collections)) {
		printed.push({ name, data: printZodInputType(schema) });
	}

	const collectionLines = printed.map((c) => {
		const body = formatObjectBody(c.data.typeSource);
		return `\t${JSON.stringify(c.name)}: ${body};`;
	});

	const kindLines = printed.map((c) => {
		const kinds = printFieldKindsObject(c.data.fields, "\t\t");
		return `\t${JSON.stringify(c.name)}: ${kinds};`;
	});

	return `/* eslint-disable */
/**
 * Generated by \`cms sync\` / @cms/astro — do not edit.
 * CMS Input shapes from stamped content.config (image/ref → CmsImage / CmsReference).
 */
import type { CmsImage, CmsReference } from "@cms/astro/collection-types";

declare module "@cms/astro/collection-types" {
\tinterface CmsCollections {
${collectionLines.join("\n")}
\t}

\tinterface CmsFieldKinds {
${kindLines.join("\n")}
\t}
}

export {};
`;
}

function formatObjectBody(typeSource: string): string {
	if (typeSource.startsWith("{")) {
		// printInner uses one tab inside; re-indent for interface body
		return typeSource
			.split("\n")
			.map((line, i) => {
				if (i === 0) return line;
				if (line === "\t}") return "\t}";
				return line;
			})
			.join("\n");
	}
	return typeSource;
}
