// Generated by Astro Dev CMS. Do not edit.
// @cms-source-hash: 893621e5768f67283437d81a951fec10f156330de1fbb7bb5e79146cbaf69261

import {
	defineCollection,
	reference,
	type SchemaContext,
} from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";

export const authorsSchema = z.object({
	name: z.string().min(1),
});

export const postsSchema = ({ image }: SchemaContext) =>
	z.object({
		title: z.string().min(1),
		draft: z.boolean().default(false),
		body: z.string(),
		cover: image().optional(),
		author: reference("authors"),
	});

const authors = defineCollection({
	loader: glob({
		base: "./src/content/authors",
		pattern: "**/*.json",
	}),
	schema: authorsSchema,
});
const posts = defineCollection({
	loader: glob({
		base: "./src/content/posts",
		pattern: "**/*.json",
	}),
	schema: postsSchema,
});

export const collections = { authors, posts };
