/**
 * @cms/routes — HTTP dispatcher + fields/protocol barrel.
 * Astro host integration lives in `@cms/astro`.
 */

/** Discovery + CMS protocol helpers (implemented in @cms/crud). */
export type {
	CmsAssetsCapability,
	CmsCapabilities,
	CmsCapabilitiesInput,
	CmsHost,
	CmsProtocol,
	CollectionSummary,
	ContentEntry,
	CreateCmsHostOptions,
	CreateCmsProtocolOptions,
	DeleteEntryFailureCode,
	DeleteEntryResult,
	DiscoverCollectionsOptions,
	DiscoveredCollection,
	EntryIdentity,
	GetCapabilitiesResult,
	GetEntryFailureCode,
	GetEntryResult,
	LoaderPathHint,
	ReadAssetResult,
	SaveEntryFailureCode,
	SaveEntryResult,
	UploadImageFailureCode,
	UploadImageInput,
	UploadImageResult,
	UpsertEntryInput,
	Writer,
} from "@cms/crud";
export {
	CMS_LOADER_HINT,
	createCmsHost,
	createCmsProtocol,
	discoverCollections,
	httpStatusForCmsErr,
	legacyStatusMapForCodes,
	memoryWriter,
	nodeFsWriter,
	resolveCmsCapabilities,
	resolveCollectionSchema,
	scanYamlEntryIds,
	withLoaderPathHint,
} from "@cms/crud";
/** Light re-export of authoring builders / FieldUi (implemented in @cms/fields). */
export {
	array,
	type BlockDefinition,
	type BlocksLayoutItem,
	type BlocksLayoutOptions,
	blocksLayout,
	boolean,
	type CollectionConfig,
	config,
	contentAssetPath,
	date,
	datetime,
	enumeration,
	type FieldMeta,
	type FieldUi,
	field,
	fieldUiRegistry,
	type I18nOptions,
	i18n,
	image,
	imageFolderFromCanonical,
	markdown,
	number,
	object,
	type ResolvedBlock,
	type ResolveLocaleOptions,
	reference,
	registerFieldUi,
	resolveBlock,
	resolveLocale,
	type SamplePostsInput,
	samplePostsSchema,
	select,
	string,
	text,
	toFormSchemas,
	toJsonSchema,
	toUiSchema,
	z,
} from "@cms/fields";
export {
	type AdaptImageOptions,
	type AdaptReferenceOptions,
	adaptImage,
	adaptReference,
} from "./adapt";
export { cmsDevOnlyGuard } from "./dev-guard";
export {
	type CmsDispatcherOptions,
	createCmsDispatcher,
} from "./dispatcher";
export {
	type CmsMiddlewareContext,
	type CmsMiddlewareHandler,
	type CmsMiddlewareNext,
	createCmsMiddleware,
} from "./middleware";
